---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
  - bin/**/*
  - vendor/**/*
  ExtraDetails: true
  TargetRubyVersion: 3.2
  UseCache: true
inherit_mode:
  merge:
  - Exclude
plugins:
- rubocop-performance
- rubocop-rake
- rubocop-rspec
- rubocop-thread_safety
require: []
inherit_from:
  - .rubocop_todo.yml
  - .rubocop/bundler.yml
  - .rubocop/gemspec.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/migration.yml
  - .rubocop/naming.yml
  - .rubocop/performance.yml
  - .rubocop/rspec.yml
  - .rubocop/rake.yml
  - .rubocop/security.yml
  - .rubocop/style.yml
  - .rubocop/threadsafety.yml


Style/DisableCopsWithinSourceCodeDirective:
  AllowedCops:
  - Style/MissingElse

Style/DocumentationMethod:
  inherit_mode:
    merge:
    - AllowedMethods
  AllowedMethods:
    - call

RSpec/ContextWording:
  inherit_mode:
    merge:
      - Prefixes
  Prefixes:
    - "on"
