AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_gem:
  docquet:
    - config/cops/bundler.yml
    - config/cops/gemspec.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/rspec.yml
    - config/cops/security.yml
    - config/cops/style.yml
    - config/cops/thread_safety.yml

inherit_from: .rubocop_todo.yml

Style/DisableCopsWithinSourceCodeDirective:
  AllowedCops:
  - Style/MissingElse

Style/DocumentationMethod:
  inherit_mode:
    merge:
    - AllowedMethods
  AllowedMethods:
    - call

RSpec/ContextWording:
  inherit_mode:
    merge:
      - Prefixes
  Prefixes:
    - "on"
